### PR TITLE
Issue with sending non ANCII chars. They was encoded wrongly.

### PR DESCRIPTION
**Pull request by witeX**
"носок" -> "=>A>:".
Issue of rest client outstream "posteroutputstream"
Solved by getting string as byte[] with proper encoding
After fix need new version release

### CODE REVIEW

**Comment by yepher** [comment]
witeX,

Good catch

**Comment by witeX** [comment]
When will be release with fix?

**Comment by yepher** [comment]
I am getting ready to build and do the release. I hope to have it mid day tomorrow.

**Comment by yepher** [comment]
This has been released:
See: https://github.com/SparkPost/java-sparkpost/releases/tag/0.12

And Nexus here:

**Pull request merged**
